### ISSUE TITLE
Cardinality backwards

### ISSUE THREAD

**Issue by mflagler** [drawdb-io/drawdb#168]
Maybe I've always thought of it wrong, but wouldn't the cardinality of one to many indicate that I have 1 record in the table with the primary key to many records in the table with the foreign key? This is currently backwards, and I have to specify this as many to one, which seems backwards to me. Am I the only one thinking this?

**Comment by 1ilit** [comment]
The program doesn't have any 'real' understanding of what the primary and foreign tables are, so the `1` and `n` labels are assigned first to the 'start table' and then to the 'end table'.

![image](https://github.com/user-attachments/assets/3e0dc90e-6c4c-48b7-a668-9587423a4941)

For example, here, since `postId` references `posts(id)`, the relationship gets created from `postId` to `id`. `Comments` becomes the 'start table' and `posts` becomes the 'end table'. So when you pick many-to-one, the `comments` side gets `n` and `posts` - `1`.

At the end of the day, one-to-many and many-to-one are the same thing depending on which table you consider first.

**Comment by 1ilit** [comment]
Feel free to reopen the issue if you still have questions
