### ISSUE TITLE
PostgreSQL import failed with named column constraint

### ISSUE THREAD

**Issue by Igorgro** [drawdb-io/drawdb#198]
The following code:
```sql
CREATE TABLE users (
    "id" SERIAL CONSTRAINT users_PK PRIMARY KEY
);
```
with named column constraint produces the following error when importing:
![image](https://github.com/user-attachments/assets/c52a2b41-442b-479f-a595-5534a39977fe)

**Comment by 1ilit** [comment]
Reported the issue https://github.com/taozhi8833998/node-sql-parser/issues/2046

**Comment by khalilmosavi** [comment]
CREATE TABLE users (
    "id" SERIAL CONSTRAINT users_PK PRIMARY KEY
);

**Comment by SjxSubham** [comment]
In PostgreSQL, column names should use single quotes or no quotes at all, and SERIAL is a valid type for auto-incrementing integers. The corrected CREATE TABLE statement for PostgreSQL is:

```
CREATE TABLE users (
    id SERIAL CONSTRAINT users_PK PRIMARY KEY
);

```



The CONSTRAINT `users_PK` part can be omitted since PostgreSQL automatically creates a primary key constraint named `users_pkey` by default. If you want to explicitly name your primary key constraint, use:

**Comment by SjxSubham** [comment]
I hope U have find Your answer, If it is then assign me to this issue and afterthat close the issue

**Comment by 1ilit** [comment]
This was fixed. Forgot to close it
